# Generated by Django 4.2.3 on 2023-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='points',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
