# Generated by Django 4.2.3 on 2023-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_competitor_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
