# Generated by Django 4.2.3 on 2023-08-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_competitor_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='points',
        ),
    ]
