# Generated by Django 4.2.3 on 2023-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_competitor_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
