# Generated by Django 4.2.3 on 2023-08-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_competitor_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_competitors',
            field=models.ManyToManyField(blank=True, null=True, related_name='picks', to='api.competitor'),
        ),
    ]
