# Generated by Django 4.2.3 on 2023-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_selected_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_competitors',
            field=models.ManyToManyField(blank=True, related_name='picks', to='api.competitor'),
        ),
    ]
