# Generated by Django 4.2.3 on 2023-09-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification_user_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_origin',
            new_name='origin_user',
        ),
    ]
