# Generated by Django 4.2.3 on 2023-09-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_origin_notification_origin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link',
            new_name='path',
        ),
    ]
