# Generated by Django 4.2.3 on 2023-10-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_link_notification_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='races',
            field=models.ManyToManyField(related_name='race_results', to='api.raceresult'),
        ),
    ]
