# Generated by Django 5.0 on 2024-01-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_season_competitors_alter_season_race_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.competitor'),
        ),
    ]
