# Generated by Django 5.0 on 2024-01-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_raceresult_competitors_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='competitors_positions',
            field=models.ManyToManyField(related_name='competitors_positions', to='api.competitor'),
        ),
    ]
