# Generated by Django 5.0 on 2024-01-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_season_competitors_alter_season_race_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='competitors_positions',
            field=models.ManyToManyField(related_name='race_results', to='api.competitor'),
        ),
        migrations.AlterField(
            model_name='season',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.competitor'),
        ),
        migrations.AlterField(
            model_name='season',
            name='race_results',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.raceresult'),
        ),
        migrations.AlterField(
            model_name='season',
            name='races',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.race'),
        ),
    ]
