# Generated by Django 5.0 on 2024-01-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_season_race_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='competitors_positions',
        ),
        migrations.AlterField(
            model_name='competitorposition',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_position', to='api.competitor'),
        ),
        migrations.AlterField(
            model_name='competitorposition',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors_positions', to='api.race'),
        ),
    ]
