# Generated by Django 5.0 on 2024-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_competitor_number_alter_competitor_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
