# Generated by Django 5.0 on 2024-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_announcementcomment_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='announcement', to='api.notification'),
        ),
    ]
