# Generated by Django 5.0 on 2024-03-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_season_current_season_selection_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='current',
        ),
        migrations.CreateModel(
            name='SelectedSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_season', to='api.season')),
            ],
        ),
    ]
