# Generated by Django 5.0 on 2024-03-25 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_season_current_selectedseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_season', to='api.season')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedSeason',
        ),
    ]
