# Generated by Django 5.0 on 2024-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_user_selected_competitors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='picks',
            field=models.ManyToManyField(blank=True, to='api.competitor'),
        ),
    ]
