# Generated by Django 5.0 on 2024-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_userpicks_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='picks',
            field=models.ManyToManyField(to='api.competitor'),
        ),
    ]
