# Generated by Django 4.2.3 on 2024-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_user_points_userpicks_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='picks',
            field=models.ManyToManyField(blank=True, to='api.competitor'),
        ),
    ]
