# Generated by Django 4.2.3 on 2024-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_userpicks_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='independant',
            field=models.BooleanField(default=False),
        ),
    ]
