# Generated by Django 4.2.3 on 2024-04-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_competitor_independant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicks',
            name='independant_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='independant_pick', to='api.competitor'),
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='picks',
            field=models.ManyToManyField(blank=True, related_name='picks', to='api.competitor'),
        ),
    ]
