# Generated by Django 5.0 on 2024-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_userpicks_independant_pick_alter_userpicks_picks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicksEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('competitor', models.ManyToManyField(blank=True, related_name='competitor', to='api.competitor')),
            ],
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='picks',
            field=models.ManyToManyField(blank=True, related_name='picks', to='api.userpicksentry'),
        ),
    ]
