# Generated by Django 5.0 on 2024-05-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userpicksentry_alter_userpicks_picks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicksentry',
            name='competitor',
        ),
        migrations.AddField(
            model_name='userpicksentry',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='api.competitor'),
        ),
    ]
