# Generated by Django 5.0 on 2024-05-29 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_userpicks_independant_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicks',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='api.season'),
        ),
        migrations.AlterField(
            model_name='userpicksentry',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competitor'),
        ),
    ]
