# Generated by Django 4.2.3 on 2024-07-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_userpicks_season_alter_userpicksentry_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='api.season'),
        ),
    ]
