# Generated by Django 4.2.3 on 2024-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_standings_season_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicks',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='season',
            name='standings',
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
        migrations.AddField(
            model_name='season',
            name='standings',
            field=models.ManyToManyField(blank=True, related_name='standings', to='api.userpicks'),
        ),
    ]
