# Generated by Django 4.2.11 on 2024-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_userpicks_position_remove_season_standings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorposition',
            name='race',
        ),
        migrations.AddField(
            model_name='competitorposition',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='competitors_positions',
            field=models.ManyToManyField(blank=True, related_name='race', to='api.competitorposition'),
        ),
        migrations.AlterField(
            model_name='competitorposition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
