# Generated by Django 4.2.11 on 2024-07-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_competitorposition_race_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='competitorposition',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='race',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
