# Generated by Django 4.2.11 on 2024-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_competitor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='points',
        ),
        migrations.AlterField(
            model_name='season',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.competitorposition'),
        ),
    ]
