# Generated by Django 4.2.11 on 2024-07-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_userpicks_independant_pick_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='independant',
        ),
        migrations.AddField(
            model_name='competitorposition',
            name='independant',
            field=models.BooleanField(default=False),
        ),
    ]
