# Generated by Django 4.2.11 on 2024-07-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_season_standings_alter_userpicks_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='api.season'),
        ),
    ]
