# Generated by Django 4.2.11 on 2024-08-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_userpicks_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorposition',
            name='independant',
        ),
        migrations.CreateModel(
            name='SeasonCompetitorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('independent', models.BooleanField(default=False)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_competitor_position', to='api.competitor')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='season',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='season', to='api.seasoncompetitorposition'),
        ),
    ]
