# Generated by Django 4.2.11 on 2024-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_competitorposition_independant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='competitors_positions',
            field=models.ManyToManyField(related_name='race', to='api.competitorposition'),
        ),
        migrations.AlterField(
            model_name='season',
            name='competitors',
            field=models.ManyToManyField(related_name='season', to='api.seasoncompetitorposition'),
        ),
    ]
