# Generated by Django 4.2.11 on 2024-08-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_race_competitors_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
