# Generated by Django 4.2.14 on 2024-10-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_race_title_alter_race_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasoncompetitorposition',
            options={'ordering': ['competitor_position__position']},
        ),
        migrations.RemoveField(
            model_name='competitorposition',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='competitorposition',
            name='points',
        ),
        migrations.RemoveField(
            model_name='seasoncompetitorposition',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='seasoncompetitorposition',
            name='points',
        ),
        migrations.RemoveField(
            model_name='seasoncompetitorposition',
            name='position',
        ),
        migrations.AddField(
            model_name='seasoncompetitorposition',
            name='competitor_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_competitor', to='api.competitorposition'),
        ),
        migrations.CreateModel(
            name='CompetitorPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_points', to='api.competitor')),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.AddField(
            model_name='competitorposition',
            name='competitor_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_position', to='api.competitorpoints'),
        ),
    ]
