# Generated by Django 4.2.14 on 2024-10-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_seasoncompetitorposition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasoncompetitorposition',
            options={'ordering': ['competitor_points__points']},
        ),
        migrations.RemoveField(
            model_name='seasoncompetitorposition',
            name='competitor_position',
        ),
        migrations.AddField(
            model_name='seasoncompetitorposition',
            name='competitor_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_competitor_position', to='api.competitorpoints'),
        ),
    ]
