# Generated by Django 4.2.14 on 2024-10-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_seasoncompetitorposition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasoncompetitorposition',
            options={'ordering': ['-competitor_points__points']},
        ),
        migrations.AlterModelOptions(
            name='userpicks',
            options={'ordering': ['-points']},
        ),
        migrations.RenameField(
            model_name='userpicks',
            old_name='independant_pick',
            new_name='independent_pick',
        ),
    ]
