# Generated by Django 4.2.14 on 2024-11-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_seasoncompetitorposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
