# Generated by Django 5.1.4 on 2024-12-08 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_season_finalized_alter_userpicks_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='top_independent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='top_rookie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpicks',
            name='rookie_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rookie_pick', to='api.competitorposition'),
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='independent_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='independent_pick', to='api.competitorposition'),
        ),
    ]
