# Generated by Django 5.1.4 on 2024-12-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_seasoncompetitorposition_rookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicks',
            name='position_change',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
