# Generated by Django 5.1.4 on 2024-12-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_rename_standings_standing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standing',
            new_name='Standings',
        ),
    ]
