# Generated by Django 5.1.4 on 2024-12-14 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_rename_standing_standings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standings',
            name='race',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='season',
        ),
        migrations.AddField(
            model_name='race',
            name='new_standings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.standings'),
        ),
        migrations.AddField(
            model_name='season',
            name='standings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.standings'),
        ),
    ]
