# Generated by Django 5.1.4 on 2024-12-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_standings_race_remove_standings_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='standings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.standings'),
        ),
    ]
