# Generated by Django 5.1.4 on 2024-12-14 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_season_standings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentseason',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='api.season'),
        ),
    ]
