# Generated by Django 5.1.4 on 2025-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_userpicks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='qualifying_positions',
            field=models.ManyToManyField(related_name='qualifying_race', to='api.competitorposition'),
        ),
        migrations.AlterField(
            model_name='race',
            name='competitors_positions',
            field=models.ManyToManyField(related_name='final_race', to='api.competitorposition'),
        ),
    ]
