# Generated by Django 5.1.4 on 2025-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_race_qualifying_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
