# Generated by Django 5.1 on 2025-01-11 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_race_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingsSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='new_standings',
        ),
        migrations.RemoveField(
            model_name='userpicks',
            name='position_change',
        ),
        migrations.AddField(
            model_name='race',
            name='standings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_standings', to='api.standingssimple'),
        ),
        migrations.CreateModel(
            name='UserPicksRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('position_change', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_picks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='standingssimple',
            name='users_picks',
            field=models.ManyToManyField(to='api.userpicksrace'),
        ),
    ]
