# Generated by Django 5.1 on 2025-01-12 00:08

import api.storage
import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=api.storage.OverwriteStorage, upload_to=api.utils.generate_image_path),
        ),
    ]
