# Generated by Django 5.1.4 on 2025-01-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpicksrace',
            options={'ordering': ['position']},
        ),
    ]
