# Generated by Django 5.1.4 on 2025-01-28 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_userpicksrace_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('notifications', models.ManyToManyField(blank=True, related_name='comments', to='api.notification')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='new_comments',
            field=models.ManyToManyField(blank=True, related_name='announcement', to='api.comment'),
        ),
        migrations.AddField(
            model_name='race',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='race', to='api.comment'),
        ),
        migrations.DeleteModel(
            name='RaceComment',
        ),
    ]
