# Generated by Django 5.1.4 on 2025-01-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20250128_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='new_comments',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_comments', to='api.announcement'),
        ),
    ]
