# Generated by Django 5.1.4 on 2025-02-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_seleniumstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumstatus',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
