# Generated by Django 5.1.4 on 2025-02-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_seleniumstatus_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleniumstatus',
            name='session_id',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
