# Generated by Django 5.1.4 on 2025-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_seleniumstatus_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleniumstatus',
            name='port',
        ),
        migrations.RemoveField(
            model_name='seleniumstatus',
            name='session_id',
        ),
        migrations.AddField(
            model_name='seleniumstatus',
            name='executor_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
