# Generated by Django 5.1.4 on 2025-02-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_remove_seleniumstatus_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicksrace',
            name='points',
            field=models.FloatField(),
        ),
    ]
