# Generated by Django 5.1.4 on 2025-03-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_userpicksrace_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='race', to='api.notification'),
        ),
        migrations.CreateModel(
            name='SeasonMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('type', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.season')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnouncementComment',
        ),
    ]
