# Generated by Django 5.1.4 on 2025-03-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_race_notifications_seasonmessages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonMessages',
            new_name='SeasonMessage',
        ),
    ]
