# Generated by Django 5.1.4 on 2025-03-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_rename_seasonmessages_seasonmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='origin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
