# Generated by Django 5.1.4 on 2025-03-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_notification_origin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={},
        ),
        migrations.RemoveField(
            model_name='race',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='race',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='race',
            name='is_sprint',
        ),
        migrations.RemoveField(
            model_name='race',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='race',
            name='qualifying_positions',
        ),
        migrations.RemoveField(
            model_name='race',
            name='standings',
        ),
        migrations.RemoveField(
            model_name='race',
            name='title',
        ),
        migrations.RemoveField(
            model_name='race',
            name='url',
        ),
        migrations.CreateModel(
            name='RaceWeekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('comments', models.ManyToManyField(blank=True, to='api.comment')),
                ('qualifying_positions', models.ManyToManyField(to='api.competitorposition')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_race_weekend', to='api.race')),
                ('sprint_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_race_weekend', to='api.race')),
                ('standings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.standingsrace')),
            ],
        ),
    ]
