# Generated by Django 5.1.4 on 2025-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_race_options_remove_race_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='race_weekends',
            field=models.ManyToManyField(related_name='season', to='api.raceweekend'),
        ),
    ]
