# Generated by Django 5.1.4 on 2025-03-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_season_race_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceweekend',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
