# Generated by Django 5.1.4 on 2025-03-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_raceweekend_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceweekend',
            name='notifications',
            field=models.ManyToManyField(related_name='race_weekend', to='api.notification'),
        ),
    ]
