# Generated by Django 5.1.4 on 2025-03-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_raceweekend_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceweekend',
            old_name='qualifying_positions',
            new_name='grid',
        ),
    ]
