# Generated by Django 5.1.4 on 2025-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_race_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceweekend',
            name='final',
        ),
        migrations.AddField(
            model_name='raceweekend',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
