# Generated by Django 5.1.7 on 2025-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_remove_raceweekend_final_raceweekend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceweekend',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='race_weekend', to='api.comment'),
        ),
    ]
