# Generated by Django 5.1.4 on 2025-03-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_alter_raceweekend_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceweekend',
            options={'ordering': ['-start']},
        ),
    ]
