# Generated by Django 5.1.7 on 2025-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_alter_raceweekend_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='race_weekends_finalize_emails',
            field=models.BooleanField(default=True),
        ),
    ]
