# Generated by Django 5.1.7 on 2025-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_rename_race_weekends_finalize_emails_user_race_weekends_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='race_weekends_emails',
            field=models.BooleanField(default=False),
        ),
    ]
