# Generated by Django 5.1.7 on 2025-03-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_set_email_notifications_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_response_emails',
            field=models.BooleanField(default=False),
        ),
    ]
