# Generated by Django 5.1.7 on 2025-03-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_user_comment_response_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='announcement_response_emails',
            field=models.BooleanField(default=False),
        ),
    ]
