# Generated by Django 5.1 on 2025-04-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_user_announcement_response_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpicks',
            options={'ordering': ['-position']},
        ),
    ]
