# Generated by Django 5.1 on 2025-04-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_userpicks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpicks',
            options={'ordering': ['position']},
        ),
    ]
